import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { manifestFor, readSeries, resetIndicatorTiles, shardYears, type SeriesManifest } from './index'
import { arevPoints } from './points'
import { resetTileHints, tieredFetch } from './source'
import type { Page } from '../plugins/types'

// Parity with the server, on bytes the real writer produced. `fixtures/` is generated by
// wdashboard-server's tests/services/fixtures/gen_indicator_tiles.py: a tiered AREV series
// written by wmarketdata's TieredSeriesStorageManager, and the points that server answers for
// the same windows, already on the wire clock. A point built here from the tiles alone has to
// equal those field for field -- the wire shift, the probability arithmetic and the signal
// thresholds are exactly the parts a second implementation gets subtly wrong.

const FIXTURES = join(import.meta.dir, 'fixtures')
const BASE = 'http://tiles.test/indicator-tiles'
const expected = JSON.parse(readFileSync(join(FIXTURES, 'expected.json'), 'utf8')) as {
  signalConfidence: number
  minNeighbours: number
  cases: { path: string; interval: string; fromStore: number; toStore: number; points: { date: number }[] }[]
}
const hint = (path: string) => ({
  path,
  point: 'arev',
  signalConfidence: expected.signalConfidence,
  minNeighbours: expected.minNeighbours
})

const realFetch = globalThis.fetch
let requests: string[] = []

beforeEach(() => {
  requests = []
  resetIndicatorTiles(BASE)
  resetTileHints()
  globalThis.fetch = (async (input: RequestInfo | URL) => {
    const url = String(input)
    requests.push(url)
    const file = join(FIXTURES, 'store', url.slice(BASE.length + 1))
    if (!url.startsWith(BASE) || !existsSync(file)) return new Response('', { status: 404 })
    return new Response(readFileSync(file))
  }) as typeof fetch
})

afterEach(() => {
  globalThis.fetch = realFetch
})

describe('indicator tiles read in the browser', () => {
  test('build exactly the points the server answers', async () => {
    for (const c of expected.cases) {
      const manifest = (await manifestFor(c.path)) as SeriesManifest
      expect(manifest).not.toBeNull()
      const rows = await readSeries(c.path, manifest, c.fromStore, c.toStore)
      expect(rows).not.toBeNull()
      const points = arevPoints(rows!, manifest.wireShiftMs, hint(c.path))
      expect(points.length).toBe(c.points.length)
      expect(points).toEqual(c.points as never)
    }
  })

  test('a daily series is shifted onto the session-dated wire clock', async () => {
    const daily = expected.cases.find((c) => c.interval === '1D')!
    const manifest = (await manifestFor(daily.path)) as SeriesManifest
    expect(manifest.wireShiftMs).toBe(7 * 3_600_000)
    expect(manifest.granularity).toBe('year')
  })

  test('refuse a window reaching past the tiles rather than answer it short', async () => {
    const c = expected.cases[0]
    const manifest = (await manifestFor(c.path)) as SeriesManifest
    expect(await readSeries(c.path, manifest, c.fromStore, manifest.coveredTo! + 1)).toBeNull()
  })

  test('shards are chosen the way the writer indexes them', () => {
    const m = { shards: { '2020': 12, '2025': 3, '2026': 2 } } as unknown as SeriesManifest
    expect(shardYears(m, Date.UTC(2026, 0, 1), Date.UTC(2026, 1, 1))).toEqual(['2025', '2026'])
    expect(shardYears(m, Date.UTC(2023, 5, 1), Date.UTC(2023, 6, 1))).toEqual(['2020'])
  })
})

describe('a stored source answered from tiles where they cover', () => {
  const c = expected.cases.find((x) => x.interval === '1h')!
  const all = c.points

  function server(calls: { from: number; to: number; limit: number }[]) {
    return async (range: { from: number; to: number }, limit: number): Promise<Page<{ date: number }>> => {
      calls.push({ ...range, limit })
      const inRange = all.filter((p) => p.date >= range.from && p.date < range.to)
      const points = inRange.slice(0, limit)
      return {
        points,
        nextFrom: points.length >= limit ? points[points.length - 1].date + 1 : null,
        tiles: hint(c.path)
      }
    }
  }

  test('the first read goes to the server; later reads below coverage never do', async () => {
    const calls: { from: number; to: number; limit: number }[] = []
    const fetch = tieredFetch('k', server(calls))
    const newest = { from: all[all.length - 50].date, to: all[all.length - 1].date + 1 }
    await fetch(newest, 5000)
    expect(calls.length).toBe(1)
    const manifest = (await manifestFor(c.path)) as SeriesManifest
    const history = { from: all[0].date, to: manifest.coveredTo! + manifest.wireShiftMs }
    const page = await fetch(history, 5000)
    expect(calls.length).toBe(1)
    expect(page.points).toEqual(all.filter((p) => p.date < history.to) as never)
  })

  test('a window across coverage takes the rest from the server and pages as one', async () => {
    const calls: { from: number; to: number; limit: number }[] = []
    const fetch = tieredFetch('k2', server(calls))
    await fetch({ from: all[all.length - 2].date, to: all[all.length - 1].date + 1 }, 10)
    const manifest = (await manifestFor(c.path)) as SeriesManifest
    const covered = manifest.coveredTo! + manifest.wireShiftMs
    const tail = all.filter((p) => p.date < covered).slice(-3)
    const window = { from: tail[0].date, to: covered + 3_600_000 * 48 }
    const page = await fetch(window, 5000)
    expect(calls.at(-1)).toEqual({ from: covered, to: window.to, limit: 5000 - 3 })
    expect(page.points).toEqual(all.filter((p) => p.date >= window.from && p.date < window.to) as never)
  })

  test('a capped tile answer continues from its last point', async () => {
    const fetch = tieredFetch('k3', server([]))
    await fetch({ from: all[all.length - 2].date, to: all[all.length - 1].date + 1 }, 10)
    const page = await fetch({ from: all[0].date, to: all[800].date }, 100)
    expect(page.points.length).toBe(100)
    expect(page.nextFrom).toBe(all[99].date + 1)
  })
})

describe('a replay', () => {
  test('reads through the server, which clamps to the replay cursor', async () => {
    const c = expected.cases[0]
    const calls: number[] = []
    const server = async (range: { from: number; to: number }, _limit: number): Promise<Page<{ date: number }>> => {
      calls.push(range.from)
      return { points: [], nextFrom: null, tiles: hint(c.path) }
    }
    let replaying = false
    const fetch = tieredFetch('replay', server, () => replaying)
    await fetch({ from: 0, to: 1 }, 10)
    replaying = true
    await fetch({ from: c.points[0].date, to: c.points[10].date }, 10)
    expect(calls.length).toBe(2)
  })
})
