// WHEN A WATCH FIRES -- the condition language, ported from the server's
// `wdashboard_server/watch/conditions.py`.
//
// This exists for exactly one reason: a BAR REPLAY has no server-side market. Its clock is
// the cursor, its market is a walk over stored bars, and no source in the server process can
// see either -- so a replay evaluates its own watches, in the browser, against the base bars
// the engine walks (client/replay/watches.ts). On a LIVE wall nothing here runs: the server
// does the watching, which is what lets a watch fire with this tab closed.
//
// A second definition of "when does this fire" is exactly the thing that quietly disagrees,
// so this is not a re-derivation -- it is a port, kept honest the way client/replay/engine.ts
// is kept honest: PARITY IS DATA. `fixtures/watch_cases.json` is generated by the Python
// (wdashboard-server `tests/watch/fixtures/gen_watch_cases.py`), run by the Python suite AND
// by `evaluate.test.ts`, and vendored here byte-identical. Change a rule there, regenerate,
// re-vendor -- nothing else keeps the two the same.
//
// Everything here is PURE: no source, no store, no clock, no chart.

import type { Condition } from './types'

/** A field's value. Numbers for anything measurable; strings for labels (a signal id, a bar
 * state), which only `==`/`!=`/`changed` accept. */
export type FieldValue = number | string

/** One field's reading. `low`/`high` bound what it covered since the previous reading; both
 * absent means the value is the whole of what happened.
 *
 * The band is how a move BETWEEN two samples is seen at all -- and it is what makes a replay
 * work, since a base bar is a coarse sample of a continuous price: `>=` and `>` read the
 * high, `<=` and `<` the low, and a crossing counts a wick that touched the level and came
 * back. */
export interface Sample {
  value: FieldValue
  low?: number
  high?: number
}

/** field -> Sample: what a source hands the evaluator for one event. */
export type Observation = Record<string, Sample>

export const MAX_DEPTH = 8

const NUMERIC_OPS: Record<string, 'high' | 'low'> = { '>': 'high', '>=': 'high', '<': 'low', '<=': 'low' }
const CROSS_OPS = ['crosses', 'crosses_above', 'crosses_below', 'changed']
const BAND_OPS = ['inside', 'outside']
const EQUALITY_OPS = ['==', '!=']

export const OPS: readonly string[] = [...Object.keys(NUMERIC_OPS), ...EQUALITY_OPS, ...CROSS_OPS, ...BAND_OPS]

/** A condition document this module refuses to evaluate. */
export class ConditionError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ConditionError'
  }
}

type Doc = Record<string, unknown>

function isDoc(value: unknown): value is Doc {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/** A finite number, and not a boolean. `Number.isFinite` where the Python asks only for a
 * non-bool int/float: JSON carries neither NaN nor an infinity, so the two can only differ
 * for a condition built by hand in this file's own language, where refusing is the better
 * answer of the two. */
function num(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null
}

function band(value: unknown): [number, number] | null {
  if (!Array.isArray(value) || value.length !== 2) return null
  const low = num(value[0])
  const high = num(value[1])
  return low === null || high === null ? null : [Math.min(low, high), Math.max(low, high)]
}

export function sample(value: FieldValue, low?: number, high?: number): Sample {
  const out: Sample = { value }
  if (low !== undefined) out.low = low
  if (high !== undefined) out.high = high
  return out
}

/** The top of the band this sample covered, or null when the value is not a number. */
export function reachHigh(s: Sample): number | null {
  if (typeof s.value === 'string') return null
  return s.high !== undefined ? Math.max(s.value, s.high) : s.value
}

export function reachLow(s: Sample): number | null {
  if (typeof s.value === 'string') return null
  return s.low !== undefined ? Math.min(s.value, s.low) : s.value
}

/** Validate a condition and return it normalised, or throw `ConditionError`.
 *
 * Called before anything is stored, so an unevaluable condition is a refusal at the moment
 * it is written rather than a silent never-fires later -- the same contract the server's
 * 400 gives a live watch. */
export function parse(document: unknown, depth = 0): Condition {
  if (depth > MAX_DEPTH) throw new ConditionError(`condition nested deeper than ${MAX_DEPTH}`)
  if (!isDoc(document)) throw new ConditionError(`condition must be an object, got ${typeof document}`)

  for (const key of ['all', 'any'] as const) {
    if (key in document) {
      const terms = document[key]
      if (!Array.isArray(terms) || terms.length === 0) {
        throw new ConditionError(`'${key}' must be a non-empty list of conditions`)
      }
      const parsed = terms.map((term) => parse(term, depth + 1))
      return (key === 'all' ? { all: parsed } : { any: parsed }) as Condition
    }
  }
  if ('not' in document) return { not: parse(document.not, depth + 1) }

  const field = document.field
  const op = document.op
  if (typeof field !== 'string' || !field) throw new ConditionError("a leaf condition needs a 'field'")
  if (typeof op !== 'string' || !OPS.includes(op)) {
    throw new ConditionError(`unknown op ${JSON.stringify(op)} (want one of ${OPS.join(', ')})`)
  }

  const value = document.value
  if (op === 'changed') {
    if (value !== undefined && value !== null) throw new ConditionError("'changed' takes no value")
    return { field, op }
  }
  if (BAND_OPS.includes(op)) {
    const pair = Array.isArray(value) && value.length === 2 ? band(value) : null
    if (pair === null) throw new ConditionError(`'${op}' takes a [low, high] pair of numbers`)
    return { field, op, value: pair }
  }
  if (EQUALITY_OPS.includes(op)) {
    if (typeof value !== 'string' && num(value) === null) {
      throw new ConditionError(`'${op}' takes a number or a string`)
    }
    return { field, op, value: value as number | string }
  }
  const threshold = num(value)
  if (threshold === null) throw new ConditionError(`'${op}' takes a number`)
  return { field, op, value: threshold }
}

/** Every field name a condition reads. Checked against a source's declared fields, so
 * "watch a field this source never emits" is refused on create rather than never firing. */
export function conditionFields(document: Condition): Set<string> {
  const doc = document as Doc
  for (const key of ['all', 'any'] as const) {
    if (key in doc) {
      const found = new Set<string>()
      for (const term of doc[key] as Condition[]) for (const name of conditionFields(term)) found.add(name)
      return found
    }
  }
  if ('not' in doc) return conditionFields(doc.not as Condition)
  return new Set([String(doc.field)])
}

/** Whether any leaf is a crossing -- i.e. whether a seed observation matters at arm time. */
export function needsPrevious(document: Condition): boolean {
  const doc = document as Doc
  for (const key of ['all', 'any'] as const) {
    if (key in doc) return (doc[key] as Condition[]).some(needsPrevious)
  }
  if ('not' in doc) return needsPrevious(doc.not as Condition)
  return CROSS_OPS.includes(String(doc.op))
}

/** A one-line human rendering, used as a watch's default name.
 *
 * Deliberately NOT in the parity fixture: it is a label, and the two languages render a
 * number differently (Python's `1.0` against JavaScript's `1`). Every caller in this client
 * passes a name of its own, so this is the fallback for a watch built by hand. */
export function describe(document: Condition): string {
  const doc = document as Doc
  for (const key of ['all', 'any'] as const) {
    if (key in doc) {
      const joiner = key === 'all' ? ' and ' : ' or '
      return (doc[key] as Condition[]).map(describe).join(joiner)
    }
  }
  if ('not' in doc) return `not (${describe(doc.not as Condition)})`
  const op = String(doc.op)
  const field = String(doc.field)
  if (op === 'changed') return `${field} changes`
  const value = doc.value
  if (BAND_OPS.includes(op) && Array.isArray(value) && value.length === 2) {
    return `${field} ${op} ${value[0]}–${value[1]}`
  }
  const words: Record<string, string> = {
    crosses: 'crosses',
    crosses_above: 'crosses above',
    crosses_below: 'crosses below'
  }
  return `${field} ${words[op] ?? op} ${String(value)}`
}

/** Is the condition satisfied by `now`? **`null` means unknowable** -- a field the
 * observation does not carry, or a crossing with nothing to cross from.
 *
 * Unknowable never fires and never counts as a False edge, which is what stops a watch armed
 * before its first observation from firing on the strength of not knowing anything. */
export function evaluate(document: Condition, now: Observation, previous?: Observation | null): boolean | null {
  const doc = document as Doc
  for (const key of ['all', 'any'] as const) {
    if (key in doc) {
      const results = (doc[key] as Condition[]).map((term) => evaluate(term, now, previous))
      if (key === 'all') {
        if (results.some((r) => r === false)) return false
        return results.some((r) => r === null) ? null : true
      }
      if (results.some((r) => r === true)) return true
      return results.some((r) => r === null) ? null : false
    }
  }
  if ('not' in doc) {
    const inner = evaluate(doc.not as Condition, now, previous)
    return inner === null ? null : !inner
  }

  const field = String(doc.field)
  const current = now[field]
  if (current === undefined) return null
  const op = String(doc.op)
  const value = doc.value

  if (EQUALITY_OPS.includes(op)) {
    const equal = current.value === value
    return op === '==' ? equal : !equal
  }
  if (BAND_OPS.includes(op)) {
    const pair = band(value)
    if (pair === null || typeof current.value === 'string') return null
    const inside = pair[0] <= current.value && current.value <= pair[1]
    return op === 'inside' ? inside : !inside
  }
  if (op in NUMERIC_OPS) {
    const threshold = num(value)
    const side = NUMERIC_OPS[op] === 'high' ? reachHigh(current) : reachLow(current)
    if (side === null || threshold === null) return null
    if (op === '>') return side > threshold
    if (op === '>=') return side >= threshold
    if (op === '<') return side < threshold
    return side <= threshold
  }

  // The crossing family: everything below needs somewhere to have crossed FROM.
  const before = previous?.[field]
  if (before === undefined) return null
  if (op === 'changed') return before.value !== current.value
  const threshold = num(value)
  if (threshold === null || typeof before.value === 'string' || typeof current.value === 'string') return null
  const high = reachHigh(current) ?? current.value
  const low = reachLow(current) ?? current.value
  const up = before.value < threshold && threshold <= high
  const down = before.value > threshold && threshold >= low
  if (op === 'crosses_above') return up
  if (op === 'crosses_below') return down
  return up || down
}
