import { expect, test } from 'bun:test'
import { resolve } from 'node:path'
import type { Condition } from './types'
import { ConditionError, type Observation, evaluate, parse } from './evaluate'

// PARITY. `watch_cases.json` is generated by wdashboard-server
// (tests/watch/fixtures/gen_watch_cases.py) from the authoritative Python and vendored here
// byte-identical; the Python suite runs the same file (tests/watch/test_cases.py). These two
// tests are the only thing standing between "the replay evaluates watches in the browser"
// and "the browser has its own opinion about when an alert fires".

interface Cases {
  conditions: Array<{ name: string; condition: Condition; now: unknown; previous: unknown; expect: boolean | null }>
  parse: Array<{ name: string; document: unknown; expect: { ok: boolean; normalised?: Condition } }>
}

const cases = (await Bun.file(resolve(import.meta.dir, 'fixtures/watch_cases.json')).json()) as Cases

/** The wire form the fixture writes an observation in: a bare number or string, or
 * `{value, low?, high?}` — the same two spellings `Sample.from_wire` accepts. */
function observation(row: unknown): Observation {
  const out: Observation = {}
  for (const [name, value] of Object.entries(row as Record<string, unknown>)) {
    out[name] =
      typeof value === 'number' || typeof value === 'string'
        ? { value }
        : (value as Observation[string])
  }
  return out
}

test('every condition case answers exactly as the server does', () => {
  expect(cases.conditions.length).toBeGreaterThan(20)
  for (const c of cases.conditions) {
    const got = evaluate(c.condition, observation(c.now), c.previous === null ? null : observation(c.previous))
    expect(`${c.name}: ${got}`).toBe(`${c.name}: ${c.expect}`)
  }
})

test('every parse case is accepted or refused exactly as the server does', () => {
  expect(cases.parse.length).toBeGreaterThan(15)
  for (const c of cases.parse) {
    if (c.expect.ok) {
      expect(`${c.name}: ${JSON.stringify(parse(c.document))}`).toBe(`${c.name}: ${JSON.stringify(c.expect.normalised)}`)
    } else {
      expect(() => parse(c.document)).toThrow(ConditionError)
    }
  }
})
