import { expect, test } from 'bun:test'
import { resolve } from 'node:path'

// The vendored watch fixture is generated by wdashboard-server; the identity check against
// the server copy is run once, by client/replay/fixtures.test.ts (one `--check` covers every
// vendored file). This asserts the provenance line, which is what an environment with no
// sibling repo can still check.

test('watch_cases.json carries its provenance', async () => {
  const doc = (await Bun.file(resolve(import.meta.dir, 'fixtures/watch_cases.json')).json()) as {
    $comment?: string
  }
  expect(String(doc.$comment)).toContain('GENERATED')
})
