"""Regenerate rules_parity.json from wdashboard-server's own rule functions.

    cd repos/wdashboard-server/main && \
      uv run python ../../klinechartspro/<worktree>/client/arevlab/fixtures/generate.py

The AREV lab's rules (client/arevlab/rules.ts) began as a port of
services/arev21outlier.py and have since moved to windows measured in DAYS, which that module
has no form of -- so what the two still share, and what this fixture pins, is:

  * the quantile (numpy's default linear method, which the lab reimplements), and
  * the entry rule and the band around a centre -- `sides()` and the prior's +/- width -- which
    decide where an arrow is printed once the lines exist.

Seeded, so a regeneration against an unchanged server is byte-identical.
"""

import json
from pathlib import Path

import numpy as np

from wdashboard_server.services import arev21outlier as o

rng = np.random.default_rng(20260916)
SIZE = 300
p = np.clip(0.5 + rng.normal(0, 0.06, SIZE), 0, 1)
# A trend in the middle, so entries come in runs and the "not in the zone already" half of the
# entry rule is exercised; NaNs, thin neighbourhoods and non-samples throughout.
p[120:170] += np.linspace(0, 0.12, 50)
p[rng.random(SIZE) < 0.03] = np.nan
n = rng.integers(0, 220, SIZE)
at_cross = rng.random(SIZE) < 0.45
rows = [
    {
        "date": 1_700_000_000_000 + i * 3_600_000,
        "p": None if not np.isfinite(p[i]) else round(float(p[i]), 6),
        "n": int(n[i]),
        "atCross": bool(at_cross[i]),
    }
    for i in range(SIZE)
]
# derive() reads p as a float; JSON null stands for NaN on the way out and back.
server_rows = [{**r, "p": np.nan if r["p"] is None else r["p"]} for r in rows]

# -- the quantile ------------------------------------------------------------------------
samples = [
    [1.0, 2.0, 3.0, 4.0],
    [7.0],
    sorted(round(float(v), 6) for v in rng.random(37)),
    sorted(round(float(v), 6) for v in rng.normal(0.5, 0.05, 200)),
]
quantiles = [
    {"sorted": s, "q": q, "value": float(np.quantile(s, q))}
    for s in samples
    for q in (0.0, 0.15, 0.5, 0.85, 0.99, 1.0)
]

# -- the band and the entry rule ---------------------------------------------------------
# `derive` with a prior centre is the server's band (+/- width) and its `sides()` in one call,
# which is exactly the pair the lab still shares. The lab reproduces it with `samplesOnly` on,
# because `sides()` counts a bar only at a sample.
centre = np.clip(0.5 + np.cumsum(rng.normal(0, 0.004, SIZE)), 0.3, 0.7)
centre[:40] = np.nan
entry_cases = []
for width in (0.03, 0.005):
    out = o.derive(server_rows, o.Variant("prior", "prior", width=width), centre=centre)
    entry_cases.append(
        {
            "width": width,
            "centreIn": [None if not np.isfinite(c) else float(c) for c in centre],
            "hi": [r["hi"] for r in out],
            "lo": [r["lo"] for r in out],
            "side": [r["side"] for r in out],
        }
    )

doc = {
    "$comment": "GENERATED by client/arevlab/fixtures/generate.py from wdashboard-server "
    "services/arev21outlier.py -- do not edit by hand.",
    "minNeighbours": o.MIN_NEIGHBOURS,
    "rows": rows,
    "quantiles": quantiles,
    "entryCases": entry_cases,
}
Path(__file__).with_name("rules_parity.json").write_text(json.dumps(doc) + "\n")
print(f"wrote {SIZE} rows, {len(quantiles)} quantile cases, {len(entry_cases)} entry cases")
