"""Regenerate rules_parity.json from wdashboard-server's own rule functions.

    cd repos/wdashboard-server/main && \
      uv run python ../../klinechartspro/<worktree>/client/arevlab/fixtures/generate.py

The AREV lab's client rules (client/arevlab/rules.ts) are a port of
services/arev21outlier.py; rules.test.ts replays this file through them so the two cannot
drift. Seeded, so a regeneration against an unchanged server is byte-identical.
"""

import json
from pathlib import Path

import numpy as np

from wdashboard_server.services import arev21outlier as o

rng = np.random.default_rng(20260915)
SIZE = 300
p = np.clip(0.5 + rng.normal(0, 0.06, SIZE), 0, 1)
# A trend in the middle, so entries come in runs and the "not in the zone already" half of the
# entry rule is exercised; NaNs, thin neighbourhoods and non-samples throughout.
p[120:170] += np.linspace(0, 0.12, 50)
p[rng.random(SIZE) < 0.03] = np.nan
n = rng.integers(0, 220, SIZE)
at_cross = rng.random(SIZE) < 0.45
rows = [
    {
        "date": 1_700_000_000_000 + i * 3_600_000,
        "p": None if not np.isfinite(p[i]) else round(float(p[i]), 6),
        "n": int(n[i]),
        "atCross": bool(at_cross[i]),
    }
    for i in range(SIZE)
]
# derive() reads p as a float; JSON null stands for NaN on the way out and back.
server_rows = [{**r, "p": np.nan if r["p"] is None else r["p"]} for r in rows]

cases = []
for variant in (
    o.Variant("rank_default", "rank", window=50, q=0.85),
    o.Variant("rank_small", "rank", window=7, q=0.7),
    o.Variant("median_default", "median", window=50, width=0.025),
    o.Variant("median_small", "median", window=12, width=0.01),
):
    out = o.derive(server_rows, variant)
    cases.append(
        {
            "kind": variant.kind,
            "window": variant.window,
            "q": variant.q,
            "width": variant.width,
            "centre": [r["centre"] for r in out],
            "hi": [r["hi"] for r in out],
            "lo": [r["lo"] for r in out],
            "side": [r["side"] for r in out],
        }
    )

# The prior's lines come from a label window the client builds differently (a count, not the
# model's training span), so what is shared -- and checked -- is everything downstream of the
# centre: the band and the entry rule.
centre = np.clip(0.5 + np.cumsum(rng.normal(0, 0.004, SIZE)), 0.3, 0.7)
centre[:40] = np.nan
out = o.derive(server_rows, o.Variant("prior", "prior", width=0.03), centre=centre)
cases.append(
    {
        "kind": "prior",
        "width": 0.03,
        "centreIn": [None if not np.isfinite(c) else float(c) for c in centre],
        "centre": [r["centre"] for r in out],
        "hi": [r["hi"] for r in out],
        "lo": [r["lo"] for r in out],
        "side": [r["side"] for r in out],
    }
)

doc = {
    "$comment": "GENERATED by client/arevlab/fixtures/generate.py from wdashboard-server "
    "services/arev21outlier.py -- do not edit by hand.",
    "minNeighbours": o.MIN_NEIGHBOURS,
    "rows": rows,
    "cases": cases,
}
Path(__file__).with_name("rules_parity.json").write_text(json.dumps(doc) + "\n")
print(f"wrote {SIZE} rows, {len(cases)} cases")
