import { describe, expect, test } from 'bun:test'

import type { Indicator, KLineData } from 'klinecharts'

import fixture from './fixtures/library_parity.json'
import nnfx from './index'

// The library indicators the NNFX systems use, against the libraries' own output -- `ta`'s Keltner
// Channel, pandas-ta's RSX, TA-Lib's SMI, LINEARREG_INTERCEPT and ATR, and MT4's ATR as the NNFX
// simulator computes it (fixtures/library_parity.json, generated by
// notes/research/NoNonSenseForex/tests/gen_nnfx_library_parity.py from the code the study ran).

const bars: KLineData[] = fixture.bars.ts.map((timestamp, i) => ({
  timestamp,
  open: fixture.bars.open[i] as number,
  high: fixture.bars.high[i] as number,
  low: fixture.bars.low[i] as number,
  close: fixture.bars.close[i] as number,
  volume: fixture.bars.volume[i] as number
}))

type Row = Record<string, number | undefined>
const templates = new Map(nnfx.map((t) => [t.name, t]))
function run(name: string, calcParams: number[]): Row[] {
  const t = templates.get(name)
  if (t === undefined) throw new Error(name)
  return (t.calc as (d: KLineData[], i: Indicator) => Row[])(bars, { calcParams } as unknown as Indicator)
}

const PARAM_ORDER: Record<string, string[]> = {
  KELTNER: ['window', 'version', 'atr', 'mult'],
  RSX: ['length'],
  SMI: ['period', 'fast', 'slow', 'signal'],
  LINREG: ['period'],
  ATR: ['period', 'method']
}

function near(actual: number | undefined, expected: number): boolean {
  return actual !== undefined && Math.abs(actual - expected) <= 1e-9 * Math.max(1, Math.abs(expected))
}

describe('parity with the libraries the NNFX study ran', () => {
  test('the fixture is the generated one, and covers all five', () => {
    expect(fixture.$comment).toContain('gen_nnfx_library_parity.py')
    expect(new Set(fixture.cases.map((c) => c.template))).toEqual(new Set(Object.keys(PARAM_ORDER)))
  })

  for (const c of fixture.cases) {
    const chart = c.chart as unknown as Record<string, number>
    const params = PARAM_ORDER[c.template].map((k) => chart[k])
    test(`${c.template}(${params.join(', ')}) -- ${c.source}`, () => {
      const rows = run(c.template, params)
      const out = c.out as unknown as Record<string, Array<number | null>>
      for (const [key, expected] of Object.entries(out)) {
        // Where the template starts its own series: `ta` averages a partial window for the original
        // Keltner bands, and TA-Lib withholds SMI until its signal exists (the template draws it
        // from its own first value). Everywhere else, the library's NaNs are the template's.
        let from = 0
        if (c.template === 'KELTNER' && key !== 'mid') from = Math.max(chart.window, chart.version === 1 ? chart.atr : 0) - 1
        const bad: Array<{ i: number; actual: number | undefined; expected: number | null }> = []
        for (let i = from; i < expected.length; i++) {
          const e = expected[i]
          const a = rows[i][key]
          if (e === null) {
            const lenient = c.template === 'SMI' && key === 'smi'
            if (a !== undefined && !lenient) bad.push({ i, actual: a, expected: e })
          } else if (!near(a, e)) bad.push({ i, actual: a, expected: e })
        }
        expect({ key, bad: bad.slice(0, 5) }).toEqual({ key, bad: [] })
        expect(expected.filter((v) => v !== null).length).toBeGreaterThan(bars.length / 3)
      }
    })
  }
})

describe('the readings the systems trade on', () => {
  test("KELTNER: the slope is the mid-line's direction, held over an unchanged bar", () => {
    const rows = run('KELTNER', [20, 0, 10, 2])
    let held = 0
    rows.forEach((r, i) => {
      const before = rows[i - 1]?.mid
      if (r.mid !== undefined && before !== undefined && r.mid !== before) held = Math.sign(r.mid - before)
      expect(r.slope ?? 0).toBe(held)
    })
    expect(new Set(rows.map((r) => r.slope).filter((s) => s !== undefined))).toEqual(new Set([1, -1]))
  })

  test('SMI: the trigger average is a plain mean of the last `ma` SMI values', () => {
    const rows = run('SMI', [39, 6, 75, 27, 3])
    for (let i = 2; i < rows.length; i++) {
      const window = [rows[i - 2].smi, rows[i - 1].smi, rows[i].smi]
      if (window.some((v) => v === undefined)) continue
      expect(rows[i].ma).toBeCloseTo((window as number[]).reduce((a, b) => a + b, 0) / 3, 10)
    }
  })

  test("LINREG: the side is the close's against the intercept", () => {
    const rows = run('LINREG', [28])
    rows.forEach((r, i) => {
      if (r.intercept === undefined) return
      expect(r.side).toBe(Math.sign(bars[i].close - r.intercept))
    })
  })

  test('ATR: the legend\'s stop is 1.5 x ATR', () => {
    for (const r of run('ATR', [14, 0])) {
      if (r.atr === undefined) continue
      expect(r.stop).toBeCloseTo(1.5 * r.atr, 12)
    }
  })
})
